"""Pibooth language handling.
"""

import io
import os
import os.path as osp
from configparser import ConfigParser
from LDS.utils import LOGGER, open_text_editor


PARSER = ConfigParser()

CURRENT = 'en'  # Dynamically set at startup

DEFAULT = {
    'br': {
        'intro': "Tirar foto",
        'intro_print': 'Ainda tem como\nimprimir esta\nfoto',
        'choose': "Escolha o formato",
        '1': "1 foto",
        '2': "2 fotos",
        '3': "3 fotos",
        '4': "4 fotos",
        'chosen': "Vamos!",
        'smile': "Sorria!",
        'processing': "Processando...",
        'print': "Imprimir foto?",
        'print_forget': "Por favor\nremova\nesta foto",
        'finished': "Obrigado!",
        'oops': "Opa! Ocorreu um erro.",
    },
    'de': {
        'intro': "Foto aufnehmen",
        'intro_print': "Du kannst dieses\nFoto immer noch\nausdrucken",
        'choose': "Wähle Dein Layout",
        '1': "1 Foto",
        '2': "2 Fotos",
        '3': "3 Fotos",
        '4': "4 Fotos",
        'chosen': "Los geht's!",
        'smile': "Bitte lächeln!",
        'processing': "Bearbeitung...",
        'print': "Foto drucken?",
        'print_forget': "Dieses Foto\nbitte löschen",
        'finished': "Danke",
        'oops': "Ups! Etwas ist schiefgelaufen",
    },
    'dk': {
        'intro': "Tag et foto",
        'intro_print': 'Eller du kan\nstadig udskrive\ndette foto',
        'choose': "Vælg dit layout",
        '1': "1 Foto",
        '2': "2 Fotos",
        '3': "3 Fotos",
        '4': "4 Fotos",
        'chosen': "Gør dig klar!",
        'smile': "Smil !",
        'processing': "Fremkalder Foto...",
        'print': "Print foto?",
        'print_forget': "Venligst\nglem dette\nfoto",
        'finished': "Tak",
        'oops': "Ups! Noget gik galt",
    },
    'en': {
        'intro': "Take a photo",
        'intro_print': "Or you can\nstill print\nthis photo",
        'choose': "Choose your layout",
        '1': "1 photo",
        '2': "2 photos",
        '3': "3 photos",
        '4': "4 photos",
        'chosen': "Let's go!",
        'smile': "Smile !",
        'processing': "Processing...",
        'print': "Print the photo?",
        'print_forget': "Please\nforget this\nphoto",
        'finished': "Thanks",
        'oops': "Oops something went wrong",
    },
    'es': {
        'intro': "Sacate Una Foto",
        'intro_print': "O Puedes\nTodavia Imprimir\nEsta Foto",
        'choose': "Elige el tipo de foto",
        '1': "1 Foto",
        '2': "2 Fotos",
        '3': "3 Fotos",
        '4': "4 Fotos",
        'chosen': "Adelante!!",
        'smile': "Sonríe!!",
        'processing': "Procesando...",
        'print': "¿Imprimir esta foto?",
        'print_forget': "Por favor\nolvida\nesta foto",
        'finished': "Gracias",
        'oops': "Maldición! Algo salió mal",
    },
    'fr': {
        'intro': "Faire une photo",
        'intro_print': "Ou sinon\ntu peux toujours\nimprimer\ncette photo",
        'choose': "Choisis ton format",
        '1': "1 photo",
        '2': "2 photos",
        '3': "3 photos",
        '4': "4 photos",
        'chosen': "C'est parti !",
        'smile': "Souriez !",
        'processing': "Préparation du montage",
        'print': "Imprimer la photo ?",
        'print_forget': "Oublie\ncette photo\ns'il te plait",
        'finished': "Merci",
        'oops': "Oups quelque chose s'est mal passé",
    },
    'hu': {
        'intro': "Akarsz egy képet",
        'intro_print': 'Vagy\nkinyomtathatja\nezt a fényképet',
        'choose': "Kérlek válassz",
        '1': "1 kép",
        '2': "2 kép",
        '3': "3 kép",
        '4': "4 kép",
        'chosen': "Készülj!",
        'smile': "Csiizzz!",
        'processing': "Feldolgozás...",
        'print': "Nyomtatod a képet?",
        'print_forget': "Kérjük,\nfelejtsd el ezt\na képet",
        'finished': "Köszi",
        'oops': "Sajnos valami hiba történt",
    },
    'it': {
        'intro': "Scatta una foto",
        'intro_print': 'Oppure puoi\nstampare\nquesta foto',
        'choose': "Scegli il formato",
        '1': "1 foto",
        '2': "2 foto",
        '3': "3 foto",
        '4': "4 foto",
        'chosen': "Andiamo!",
        'smile': "Sorridi!",
        'processing': "Elaborazione...",
        'print': "Stampo la foto?",
        'print_forget': "Per favore\nignora questa\nfoto",
        'finished': "Grazie",
        'oops': "Oops qualcosa è andato storto",
    },
    'nl': {
        'intro': "Neem een foto",
        'intro_print': "Of je kan\nnog altijd \ndeze foto printen",
        'choose': "Kies een ontwerp",
        '1': "1 foto",
        '2': "2 foto’s",
        '3': "3 foto’s",
        '4': "4 foto’s",
        'chosen': "We gaan ervoor!",
        'smile': "Lachen!",
        'processing': "Verwerken...",
        'print': "Print de foto?",
        'print_forget': "Vergeet\ndeze foto\nalstublieft",
        'finished': "Bedankt",
        'oops': "Oeps er ging iets mis",
    },
    'no': {
        'intro': "Ta et bilde",
        'intro_print': 'Eller du kan\nfremdeles printe\ndette bildet',
        'choose': "Velg ditt utseende",
        '1': "1 bilde",
        '2': "2 bilder",
        '3': "3 bilder",
        '4': "4 bilder",
        'chosen': "Start!",
        'smile': "Smil !",
        'processing': "Behandler...",
        'print': "Printe bildet?",
        'print_forget': "Glem\ndette\nbildet",
        'finished': "Takk",
        'oops': "Ops, noe gikk galt",
    },
    'pt': {
        'intro': "Tira uma foto",
        'intro_print': 'Ainda podes\nimprimir esta\nfoto',
        'choose': "Escolhe o teu formato",
        '1': "1 foto",
        '2': "2 fotos",
        '3': "3 fotos",
        '4': "4 fotos",
        'chosen': "Vamos!",
        'smile': "Sorri!",
        'processing': "A processar...",
        'print': "Imprimir foto?",
        'print_forget': "Por favor\nesqueçe-te\ndesta foto",
        'finished': "Obrigado!",
        'oops': "Oops, ocorreu um erro.",
    },
}